add minimuxer_set_location for set ios location
SideStore/minimuxer pull request #5
Opened 2023-02-14 03:57 UTC by hw-1

2023-02-14 04:23 UTC, naturecodevoid requested changes
Thanks for the contribution! However, I’m a bit confused why we would need this function. minimuxer is only supposed to be used in SideStore. If you want to use it outside of SideStore, please fork minimuxer instead of making a PR.

If this is intended to be used in SideStore, what functionality would it serve? I don’t see the use in manually setting location.

2023-02-14 04:23 UTC, naturecodevoid commented on src/location.rs
> +pub unsafe extern "C" fn minimuxer_isconnect() -> libc::c_int {
Please see minimuxer_ready: https://github.com/SideStore/minimuxer/pull/4/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R79

2023-02-17 19:27 UTC, naturecodevoid commented
Hey @hw-1, I discussed with some other team members and we are planning to add this as a feature eventually, but I think this PR will need some code cleanup first. It will also need an implementation in SideStore, but I may be able to do that.

2023-04-28 22:21 UTC, silxl reviewed
Access

2024-09-10 08:04 UTC, closed without merging